# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BPM' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BPM
  pod 'ChameleonFramework/Swift', '~> 2.1'
  pod 'FontAwesome.swift'
  
  target 'BPMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BPMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
